FROM debian:bookworm

RUN apt-get update && apt-get install -y nginx openssl && \
    rm -rf /var/lib/apt/lists/*

COPY conf/ssl/server.crt /etc/ssl/certs/
COPY conf/ssl/server.key /etc/ssl/private/
COPY conf/nginx.conf /etc/nginx/nginx.conf

EXPOSE 443
CMD ["nginx", "-g", "daemon off;"]
